### ISSUE TITLE
The Correspondence button next to assignments is confusing

### ISSUE THREAD

**Issue by yellowsquash** [SantaPoneCentralDev/santaponecentral#48]
![image](https://user-images.githubusercontent.com/74082164/98682049-592c3e80-235b-11eb-9964-5e4537c343c7.png)

Looking at the above, my first thought is that this is a PM with my assignee, which I've been told is not the intention. Instead it is supposed to be correspondence with the event organizers regarding this specific assignment. I think this is unclear.

Some suggestions that may help:

* Change the `Correspondence` to `Admin Correspondence`
* Include a note above the chat window with something along the lines of "This is a private chat between (you) and the event organizers regarding your assignment: "XXX for the Gift Exchange"

Otherwise I forsee anons getting pissy about being able to chat with their assignees + people attempting to reach out to their assignee but their messages going to the wrong person.

**Comment by SantaPoneCentralDev** [comment]
Admin Correspondence would be a nice change for profiles. Good suggestion for sure. Ill look into that. Any other more site thematic names you can think of? I always enjoy a bit of creativity in that sense

**Comment by SantaPoneCentralDev** [comment]
c70a5a0b49fb085dbb90284904a0bb3f56516d43

Aha, came up with a good name. "Admin Intelligence"
Informative and thematic; the best of both worlds. Ill close this issue if that is resolved then?

**Comment by yellowsquash** [comment]
Thanks for changing the button name. What did you think about the second point? I still think it would be useful.

**Comment by SantaPoneCentralDev** [comment]
510e3209b415127afc5cbc6e6421cf48c50efa2d

Modified that here. Didn't use the exact wording, but made it clearer as such

**Comment by yellowsquash** [comment]
Wording looks good to me - thanks!
