### ISSUE TITLE
Allow middle mouse click to open link in new tab on UI buttons

### ISSUE THREAD

**Issue by yellowsquash** [SantaPoneCentralDev/santaponecentral#52]
Often I'll middle-click to open up a link in a new tab. I find though that the UI buttons on SantaPoneCentral don't do anything when middle-clicked on.

For instance on the mission boards page, there's a whole lot of thread links that I'd like up open up several at a time for. However, middle-clicking does nothing, while left-clicking opens up a new tab *but with my browser changing to that new tab*.

The above means that every thread link I click on, I get taken to the new tab, before I have to go back to SPC, click another thread, go back to SPC. If I'm trying to open a significant number of links up at once it can get tiring.

So can we have middle-click on link buttons open a new tab and not steal focus? ^:)

**Comment by SantaPoneCentralDev** [comment]
Ill see what I can do. A solution currently is just the standard hold ctrl as you click the links, which opens tabs and keeps you on the current page

**Comment by SantaPoneCentralDev** [comment]
Hmm, might have to put this one on the backlog. Material buttons dont like the typical (auxclick) event for middle mouse button stuff. I doubt you want windows opening on a right click and all. The hold ctrl and click thing though should still work 100%. Ill keep this issue up in case that ever comes to a fix though
